### ISSUE TITLE
how to proxy jitpack.io through nexus

### ISSUE THREAD

**Issue by jgangemi** [jitpack/jitpack.io#506]
we run a private nexus repository at work and proxy maven central, etc. i'm not having any lucky setting up a proxy and was hoping you could provide the correct configuration settings.

thanks!!

**Comment by saulvargas** [comment]
I have a similar situation at work, the following lines in my settings.xml fixed it for me:

```
 		<mirror>
			<id>COMPANY-nexus</id>
			<mirrorOf>*,!jitpack.io</mirrorOf>
			<url>COMPANY MIRROR</url>
		</mirror>
		<mirror>
			<id>jitpack.io</id>
			<mirrorOf>jitpack.io</mirrorOf>
			<url>https://jitpack.io</url>
		</mirror>
```

**Comment by TheCK** [comment]
I've run into the same issue. I'm suspecting the problem is that jitpack does not allow indexing of it's build artifacts.

Any progress on this?

**Comment by jitpack-io** [comment]
It's true that jitpack doesn't publish an index though not sure why that would prevent proxying. 
There are some settings.xml changes mentioned earlier. Do those help at all?

**Comment by jgangemi** [comment]
if you're trying to mirror through nexus, there is an option to turn off generating the remote index. i have to do that in order to mirror one of `adobe`'s sites.

**Comment by TheCK** [comment]
The fix for the settings.xml does indeed work. however that just circumvents our company's nexus altogether. 

Nexus does seem to create an index and if it does not have one does not seem to look for any artifacts for that repo. I will try to find the option to disable the remote index as @jgangemi suggested. However we are running an old version of Nexus, so I have to see if it supports that.

Thanks for your suggestions so far.

**Comment by TheCK** [comment]
OK I've tried to turn off indexing. But Nexus is still refusing to talk to jitpack.io. When I save the configuration it tries do communicate with jitpack.io but encounters some error. No idea which since it's HTTPS. And Nexus does not show a warning or error anywhere.
Whenever I try to get the dependency from Nexus no further communication between Nexus and jitpack.io happens.

**Comment by arbitorius** [comment]
Same Problem here... no luck proxying jitpack via Nexus.
The most convenient solution i found , which is just a tuned version of the above mentioned which bypasses nexus, is to exclude jitpack.io from the main mirror.
```xml
  <mirror>
    <id>nexus</id>
    <mirrorOf>*,!jitpack.io</mirrorOf>
    <url>http://company.com/nexus</url>
  </mirror>
```
And to create a profile which is added to the active profiles. This way you only have to put the desired dependencies into your pom and omit the repository declaration.
```xml
  <profile>
    <id>jitpack</id>
    <repositories>
      <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
      </repository>
    </repositories>
  </profile>

  <activeProfiles>
       <activeProfile>jitpack</activeProfile>
  </activeProfiles>
```

**Comment by jitpack-io** [comment]
Hi all,

We've deployed a fix that should solve proxying via Nexus: https://issues.sonatype.org/browse/NEXUS-9890

Tested using Nexus 2 and 3.

To proxy JitPack:
 1. Add `https://jitpack.io` as a new maven2 (proxy) repository in Nexus ([example](https://cloud.githubusercontent.com/assets/11161622/21227346/7f03cf18-c2d1-11e6-8827-a1af3063ef0a.png))
 2. Add that repository to Maven-public group   ([example](https://cloud.githubusercontent.com/assets/11161622/21227396/b244c242-c2d1-11e6-96e9-a177c5b7d8bc.png)) 

Let us know if you still experience any issues.

![image](https://cloud.githubusercontent.com/assets/11161622/21227415/d3645b54-c2d1-11e6-9fc8-6a3f5f677ab5.png)

**Comment by ben-xo** [comment]
Just wanted to say that @saulvargas answer for settings.xml is still relevant and useful, and that's what I came here for.

**Comment by l3ender** [comment]
@jitpack-io's answer (https://github.com/jitpack/jitpack.io/issues/506#issuecomment-267338823) worked for us using Nexus 3.15.

**Comment by Lonzak** [comment]
I have nexus 3.59 but it still doesn't sync with jitpack :-(
